export const ADD_TODO = 'ADD_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TRIMMED_TODO = 'TRIMMED_TODO';
export const ADD_TODO_STARTED = 'ADD_TODO_STARTED';
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_DONE = 'FETCH_TODOS_DONE';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';