# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877326364b1e549d30fbbd8916dd80fe3fb5921d26661ac22a37e17da10f0aeee91e55eca947006cc2bcde97f380fb7c4b0430e9572df1e028098fb578a890af

test:
  secret_key_base: f00acc7eed8e3fe42c7f6a1e101061124f6702fab74be1495298c5cee9371bd6c4475c594b4b5374f8e565b6b55c7359be43fe4ceb99804d733fef0790cb0762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
